# Uncomment the next line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'

use_frameworks!
use_modular_headers!

inhibit_all_warnings!

target 'DSBridge-Swift' do
    pod "dsBridge"
    pod 'SnapKit'
    pod 'SwiftyJSON'
   # pod 'Tiercel', '~> 3.2.0'
#  pod 'Alamofire', '~> 4.9.1'
#  pod 'CocoaAsyncSocket', '~> 7.6.4'
#  pod 'CocoaLumberjack', '~> 3.6.1'
##  pod 'FLEX', '~> 4.1.1'
#  pod 'HandyJSON', "=5.0.2-beta"
#  pod 'DeviceKit', '~> 3.1.0'
end

#post_install do |installer_representation|
#    installer_representation.pods_project.targets.each do |target|
#        if target.name == 'ObjectMapper+Realm'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '5.0'
#            end
#        end
#    end
#end

# post_install do |installer|
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['ENABLE_BITCODE'] = 'YES' #flutter support bitcode from v1.17.0
#     end
#   end
# end
